//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	2	5	11
        ///
        ///1	4	8
        ///
        ///2	0	3	14
        ///
        ///3	2	6	10
        ///
        ///4	1	5	15
        ///
        ///5	0	4	11	19
        ///
        ///6	3	7	12
        ///
        ///7	6	13	17
        ///
        ///8	1	15
        ///
        ///9	13
        ///
        ///10	3	12	18
        ///
        ///11	0	5	14	21
        ///
        ///12	6	10	17	22
        ///
        ///13	7	9	16	20
        ///
        ///14	2	11	18
        ///
        ///15	4	8	19
        ///
        ///16	13	25
        ///
        ///17	7	12	20	24
        ///
        ///18	10	14	22	27
        ///
        ///19	5	15	21	29
        ///
        ///20	13	17	25	28
        ///
        ///21	11	19	23
        ///
        ///22	12	18	24	31
        ///
        ///23	21	27	35
        ///
        ///24	17	22	28
        ///
        ///25	16	20	26	30
        ///
        ///26	25	32
        ///
        ///27	18	23	31	36
        ///
        ///28	20	24	30	37
        ///
        ///29	19	33	35
        ///
        ///30	25	28	32	40
        ///
        ///31	22	27	34	39
        ///
        ///32	26	30	45
        ///
        ///33	29	42	43
        ///
        ///34	31	37	44
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string crosses {
            get {
                return ResourceManager.GetString("crosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warszawa {
            get {
                object obj = ResourceManager.GetObject("warszawa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warszawa2 {
            get {
                object obj = ResourceManager.GetObject("warszawa2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warszawa3 {
            get {
                object obj = ResourceManager.GetObject("warszawa3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
